import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/providers/next-auth/NextAuthProvider";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { theme } from "../../theme";
import { Header, Footer, Container } from "@/shared/layout";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section className="core-section">
					<MantineProvider theme={theme}>
						<NextAuthProvider>
							<Header />
							<Container>{children}</Container>
							<Footer />
						</NextAuthProvider>
					</MantineProvider>
				</section>
			</body>
		</html>
	);
}
