import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider, TantackQueryProvider } from "@/providers";
import { MantineProvider } from "@mantine/core";

import { Header, Footer } from "@/shared/layout";

import "./reset.css";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Scan Project",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans`}>
				<section className="core-section">
					<MantineProvider>
						<NextAuthProvider>
							<TantackQueryProvider>
								<Header />
								{children}
								<Footer />
							</TantackQueryProvider>
						</NextAuthProvider>
					</MantineProvider>
				</section>
			</body>
		</html>
	);
}
